# Generated by Django 5.1.2 on 2024-10-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
